---
title: "R Notebook"
output: html_notebook
---

1. Vectores y matrices
1.1
```{r}
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)
```
1.2
```{r}
students_vector <- c(student_1,student_2, student_3, student_4, student_5)
students_vector
```
1.3
```{r}
students_matrix <- matrix(students_vector,byrow=TRUE,nrow=5)
students_matrix
```

2. Nombrado de matriz
2.1
```{r}
name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones","Tom Hill")
name_courses_legal_age <-c ("TIC", "Accounting", "Psychology", "Ethics","Legal_age")
```
2.2
```{r}
rownames(students_matrix) <- name_students
colnames(students_matrix) <- name_courses_legal_age
students_matrix
```
3. rowSums, cbind

3.1
```{r}

total_grade_student <- rowSums(students_matrix[,1:4] )
total_grade_student
```

3.2
```{r}

result_students <- cbind(students_matrix ,total_grade_student)
result_students
```

4. Seleccionando elementos de una matriz

4.1
```{r}

selected_elements <- students_matrix[c(1,3,5),c(2,4)]
selected_elements

```

5. Data frames
5.1
```{r}

students_grades_df <- data.frame(result_students)
students_grades_df
```
5.2

```{r}
subset(students_grades_df, subset = Accounting > 80 & Legal_age == TRUE)
```

6. Funciones, Condicionales y Bucles

6.1
```{r}
students_projection <- function(){
  for (row in 1:nrow(result_students)) {
    for(col in 1:4){
      print(paste("On row ", row, "and column ", col, " contains ", result_students[row,col]))
    }
  }
}
students_projection()
```
6.2
```{r}
students_projection <- function(){
  for (row in 1:nrow(result_students)) {
    for(col in 1:4){
      if(result_students[row,col] <= 45){
        print("Student at risk")
      } else if(result_students[row,col] > 45 & result_students[row,col] < 61){
        print("Student may be approved")
      } else if(result_students[row,col] >= 61){
        print("Student approved")
      }
      
    }
  }
}

```
6.3
```{r}

students_projection()
```

